### ISSUE TITLE
Fail with generation of RUssian map

### ISSUE THREAD

**Issue by alrusdi** [theSage21/pytongue#1]
$ python3 map_generator.py
...
{'**build_class**': '**build_class**'}
Traceback (most recent call last):
  File "map_generator.py", line 42, in <module>
    ask_mapping(list(set(keys + needed)))
  File "map_generator.py", line 16, in ask_mapping
    translation = translator.translate(token)
  File "/pytongue/languages/translate.py", line 38, in translate
    return ' '.join(self._get_translation_from_google(s) for s in self.source_list)
TypeError: sequence item 0: expected str instance, bool found

**Comment by theSage21** [comment]
@alrusdi I have also experienced this error for other languages. It arises from the [python-google-translate](https://github.com/terryyin/google-translate-python) submodule which is used to provide translation.

I am not sure why this happens and am still looking into it. I will add a quick fix for this so that the mapping still gets generated and the failures can be written by hand.

_edit_
13b42dbe1257c4e72560154e2e2ee335f32066b3 is a quick fix for this.
