### ISSUE TITLE
can pytounge support Marathi ?

### ISSUE THREAD

**Issue by sidjad** [theSage21/pytongue#5]
I am from Maharashtra , I am looking python code in Marathi . so any chance to code in python using Marathi ?

**Comment by theSage21** [comment]
@sidjad Yes. Pytongue should be able to support Marathi. As per the [wiki list](https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes) Marathi has a code of `mr`.  
Hence following the instructions in pytongue, 
1. Download pytongue using git or the zip file
2. `cd languages`
3. `python3 map_generator.py`
4. Since we want marathi, we enter the code `mr`
5. After the language map has been generated, you can create any plaintext file
   and put the first line as `# MR` to use marathi
6. When you have completed writing your program, you can run it using `./pytongue.sh myfile.py`

That should help you get along.

In case you are lost, run `make_example.py` using `python3 make_examples.py` after creating the language map. That should generate a default marathi program in the examples folder and should be listed as `MR_example.py`

**Comment by theSage21** [comment]
@sidjad I'm closing this issue now.
